/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef ROOAUDIO_AUTODEFS_H
#define ROOAUDIO_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ROOAUDIO_NAME "rooAudio"
#define S3E_EXT_ROOAUDIO_HASH 0x1b8e3447

#endif /* !ROOAUDIO_AUTODEFS_H */
