/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "rooAudio.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       void(*rooAudio_init_t)();
typedef       void(*rooAudio_play_t)(const char * filename);
typedef       void(*rooAudio_stop_t)();

/**
 * struct that gets filled in by rooAudioRegister
 */
typedef struct rooAudioFuncs
{
    rooAudio_init_t m_rooAudio_init;
    rooAudio_play_t m_rooAudio_play;
    rooAudio_stop_t m_rooAudio_stop;
} rooAudioFuncs;

static rooAudioFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x1b8e3447, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: rooAudio");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x1b8e3447, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool rooAudioAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

void rooAudio_init()
{
    IwTrace(ROOAUDIO_VERBOSE, ("calling rooAudio[0] func: rooAudio_init"));

    if (!_extLoad())
        return;

    g_Ext.m_rooAudio_init();
}

void rooAudio_play(const char * filename)
{
    IwTrace(ROOAUDIO_VERBOSE, ("calling rooAudio[1] func: rooAudio_play"));

    if (!_extLoad())
        return;

    g_Ext.m_rooAudio_play(filename);
}

void rooAudio_stop()
{
    IwTrace(ROOAUDIO_VERBOSE, ("calling rooAudio[2] func: rooAudio_stop"));

    if (!_extLoad())
        return;

    g_Ext.m_rooAudio_stop();
}
